version: "3.7"
services:
  joinbus:
    container_name: joinbus
    image: otavio27/joinbus:0.0.3
    restart: always
    ports:
      - 9750:80
    environment:
      Group: "https://onibus.info/api/routes/group"
      Timetable: "https://onibus.info/api/timetable/"
      Routes: "https://onibus.info/api/routes/"
      Stoptripslist: "https://onibus.info/api/stoptrips/"
      Stopsnear: "https://onibus.info/api/stopsnear?lat="
      Referer: "https://onibus.info/mapa/"
      Host: "onibus.info"