version: '3'

services:
  app_joinbus:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - Group="https://onibus.info/api/routes/group"
      - Timetable="https://onibus.info/api/timetable/"
      - Routes="https://onibus.info/api/routes/"
      - Stoptripslist="https://onibus.info/api/stoptrips/"
      - Stopsnear="https://onibus.info/api/stopsnear?lat="
      - Referer="https://onibus.info/mapa/"
      - Host="onibus.info"

    ports:
      - "8750:80"
    restart: always
