version: '3.7'
services:
  bus:
    build: .
    restart: always
    ports:
      - '8290:80'
    deploy:
      resources:
        limits:
          memory: 512M  
        reservations:
          memory: 256M  
