image:
	docker-compose up --build -d --remove-orphans
up:
	docker-compose up -d 
clear:
	docker image prune -a
logs:
	docker-compose logs -f
list:
	docker ps
iterative:
	docker exec -it front_bus_1 sh